In [ ]:
import numpy as np
arr= np.array('one')    
arr

array('one', dtype='<U3')

In [ ]:
arr.ndim   # Zero dimensional array

0

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.ndim     # one dimensional array

1

In [ ]:
a.shape    # means it has 4 columns and 1 row

(4,)

In [ ]:
a.size     # Total number of elements

4

In [ ]:
# Indexing
a[3]

4

In [ ]:
a[2] + a[1]

5

In [ ]:
# Slicing
a[2:]

array([3, 4])

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.ndim    # Two dimensional array

2

In [ ]:
b.shape   # Two rows and three columns

(2, 3)

In [ ]:
b.size   # Matrix total elements

6

In [ ]:
# Indexing(2D)
b[0,1]

2

In [ ]:
# Slicing(2D)
b[1:,1:]

array([[5, 6]])

In [ ]:
# np- numpy     random- package    randint- library
d=np.random.randint(0,10,6)     # any 6 random numbers between 0 to 10
d

array([2, 0, 8, 1, 1, 6])

In [ ]:
e= np.random.randint(0,10, size=(2,2))   # 2D random matrix
e

array([[2, 5],
       [4, 8]])

In [ ]:
d.reshape(2,3)   # Reshape existing 1D into 2D

array([[4, 2, 2],
       [5, 4, 4]])

In [ ]:
d   # Our array is back to normal, that means reshaping done was not permanent change

array([4, 2, 2, 5, 4, 4])

In [ ]:
# Let's store the reshaped array in variable d to make it permanent
d=d.reshape(2,3)

In [ ]:
d               #voila!

array([[4, 2, 2],
       [5, 4, 4]])

In [ ]:
d.dtype      # int 64 means in d we can store 64bits integers

dtype('int64')

In [ ]:
d.astype('float32')   # changing the type into float 32bits

array([[4., 2., 2.],
       [5., 4., 4.]], dtype=float32)

In [ ]:
x= np.ones(5)     # White colour
x                 # ones give float output

array([1., 1., 1., 1., 1.])

In [ ]:
y= np.zeros(5)  # black colour
y               # Float output

array([0., 0., 0., 0., 0.])

In [ ]:
z= np.zeros([2,2])   # 2D matrix
z

array([[0., 0.],
       [0., 0.]])

In [1]:
import pandas as pd
df= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML notebooks/train.csv")
df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# Important, using
f1= np.sum((df['Sex']=='female')&(df['Survived']==1))
f0= np.sum((df['Sex']=='female')&(df['Survived']==0))
m1= np.sum((df['Sex']=='male')&(df['Survived']==1))
m0= np.sum((df['Sex']=='male')&(df['Survived']==0))
print(f1)
print(f0)
print(m1)
print(m0)